export const pricingCardData = [
  {
    name: 'Basic',
    title: 'the production company charges a fixed',
    money: '$1,200',
    moneyTitle: '/per project',
    plane: 'select plan',
    includes: 'Includes:',
    Pre_production: 'Pre-production',
    limited: 'Limited',
    production: 'Production',
    post_production: 'Post-production',
    crew_Members: 'Crew Members',
    crew_MembersMan: '1-3',
    equipment: 'Equipment',
    equipmentName: 'Basic',
    deliveryTime: 'Delivery Time',
    Revisions: 'Revisions',
    RevisionsMan: '1',
    delivery_Time: '2-4 weeks',
  },
  {
    name: 'Pro',
    title: 'the production company charges a fixed',
    buttonText: 'Recommended',
    money: '$5,000',
    moneyTitle: '/per project',
    plane: 'select plan',
    includes: 'Includes:',
    Pre_production: 'Pre-production',
    limited: 'Full',
    production: 'Production',
    post_production: 'Post-production',
    crew_Members: 'Crew Members',
    crew_MembersMan: '4-8',
    equipment: 'Equipment',
    equipmentName: 'Basic',
    deliveryTime: 'Delivery Time',
    delivery_Time: '1-2 weeks',
    Revisions: 'Revisions',
    RevisionsMan: '2-3',
  },
  {
    name: 'Pro',
    title: 'the production company charges a fixed',
    money: 'Custom Quote',
    plane: 'custom quote',
    includes: 'Includes:',
    Pre_production: 'Pre-production',
    limited: 'Full + Customized',
    production: 'Production',
    post_production: 'Post-production',
    crew_Members: 'Crew Members',
    crew_MembersMan: 'customized',
    equipment: 'Equipment',
    equipmentName: 'customized',
    deliveryTime: 'Delivery Time',
    delivery_Time: 'customized',
    Revisions: 'Revisions',
    RevisionsMan: 'customized',
  },
];
